# ============================================================
# Jupyter Notebook Script: predictive_maintenance_notebook.py
# Run this to create the full notebook programmatically.
#
# Usage:  python notebooks/create_notebook.py
# ============================================================

import json
import os

cells = [
    # ─── Title Cell ──────────────────────────────────────────
    {
        "cell_type": "markdown",
        "source": [
            "# 🤖 AI-Powered Predictive Maintenance for IoT Devices\n",
            "\n",
            "**Author:** Your Name  \n",
            "**Date:** 2026  \n",
            "**Domain:** Industrial IoT | Machine Learning | Data Science\n",
            "\n",
            "---\n",
            "\n",
            "## 🎯 Objective\n",
            "Predict machine failures BEFORE they happen using sensor data (temperature, vibration, pressure, RPM, oil level).\n",
            "\n",
            "## 🏭 Industry Relevance\n",
            "- **Manufacturing:** Prevent conveyor belt failures, motor breakdowns\n",
            "- **Aviation:** Predict jet engine component wear\n",
            "- **Power Plants:** Monitor turbine health\n",
            "- **Automotive:** Detect transmission and engine issues early\n",
            "\n",
            "## 📋 Workflow\n",
            "```\n",
            "IoT Sensors → Data Generation → Preprocessing → Feature Engineering\n",
            "           → Model Training → Failure Prediction → Alerts → Visualization\n",
            "```",
        ],
        "metadata": {},
    },
    # ─── Setup Cell ──────────────────────────────────────────
    {
        "cell_type": "markdown",
        "source": ["## ⚙️ Step 1: Setup & Imports"],
        "metadata": {},
    },
    {
        "cell_type": "code",
        "source": [
            "import sys, os\n",
            "sys.path.insert(0, os.path.join('..', 'src'))\n",
            "\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "import warnings\n",
            "warnings.filterwarnings('ignore')\n",
            "\n",
            "from data_generator   import generate_sensor_data\n",
            "from preprocessor     import preprocess_pipeline\n",
            "from feature_engineer import feature_engineering_pipeline, get_feature_columns\n",
            "from model_trainer    import prepare_data, train_all_models, save_model\n",
            "from predictor        import predict_failure, generate_alerts, print_alert_summary\n",
            "from visualizer       import *\n",
            "\n",
            "print('✅ All imports successful!')\n",
            "print(f'NumPy: {np.__version__}')\n",
            "print(f'Pandas: {pd.__version__}')",
        ],
        "metadata": {},
        "outputs": [],
        "execution_count": None,
    },
    # ─── Data Generation ─────────────────────────────────────
    {
        "cell_type": "markdown",
        "source": [
            "## 📡 Step 2: Generate Synthetic IoT Sensor Data\n",
            "\n",
            "> **What is this?**  \n",
            "> Since we don't have real industrial machines, we simulate IoT sensor readings.\n",
            "> The simulation includes **gradual degradation patterns** — sensors worsen over time, just like real machines.\n",
            "\n",
            "**Sensors simulated:**\n",
            "| Sensor | Unit | Normal Range | Failure Indicator |\n",
            "|--------|------|-------------|-------------------|\n",
            "| Temperature | °C | 60–85 | > 100°C |\n",
            "| Vibration | mm/s | 0.2–0.8 | > 1.5 mm/s |\n",
            "| Pressure | PSI | 90–110 | < 70 PSI |\n",
            "| RPM | rotations/min | 1400–1600 | < 1200 |\n",
            "| Oil Level | % | 75–95 | < 30% |",
        ],
        "metadata": {},
    },
    {
        "cell_type": "code",
        "source": [
            "# Generate 60 days of sensor data for 5 machines\n",
            "df_raw = generate_sensor_data(\n",
            "    n_machines=5,\n",
            "    days=60,\n",
            "    samples_per_hour=1,\n",
            "    failure_probability=0.05,\n",
            "    save_path='../data/sensor_data.csv'\n",
            ")\n",
            "\n",
            "print('\\nFirst 5 rows:')\n",
            "df_raw.head()",
        ],
        "metadata": {},
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "source": [
            "# Dataset info\n",
            "print('Dataset Shape:', df_raw.shape)\n",
            "print('\\nData Types:')\n",
            "print(df_raw.dtypes)\n",
            "print('\\nClass Distribution:')\n",
            "print(df_raw['failure'].value_counts())\n",
            "print(f'\\nFailure Rate: {df_raw[\"failure\"].mean()*100:.2f}%')",
        ],
        "metadata": {},
        "outputs": [],
        "execution_count": None,
    },
    # ─── Preprocessing ───────────────────────────────────────
    {
        "cell_type": "markdown",
        "source": [
            "## 🔧 Step 3: Data Preprocessing\n",
            "\n",
            "> **Why preprocess?**  \n",
            "> Raw sensor data has noise, missing values, and extreme outliers.\n",
            "> We must clean it before feeding it to a model.\n",
            "\n",
            "**Steps:**\n",
            "1. Handle missing values (forward-fill)\n",
            "2. Clip outliers (Z-score > 3.5)\n",
            "3. Validate physical ranges (RPM ≥ 0, Oil Level 0–100)",
        ],
        "metadata": {},
    },
    {
        "cell_type": "code",
        "source": [
            "df = preprocess_pipeline('../data/sensor_data.csv')\n",
            "df.head()",
        ],
        "metadata": {},
        "outputs": [],
        "execution_count": None,
    },
    # ─── Visualization 1 ─────────────────────────────────────
    {
        "cell_type": "markdown",
        "source": ["## 📊 Step 4: Exploratory Data Analysis"],
        "metadata": {},
    },
    {
        "cell_type": "code",
        "source": [
            "import matplotlib\n",
            "matplotlib.use('inline')\n",
            "%matplotlib inline\n",
            "\n",
            "# Sensor time series for Machine 1\n",
            "mdf = df[df['machine_id'] == 1]\n",
            "\n",
            "fig, axes = plt.subplots(5, 1, figsize=(14, 10), sharex=True)\n",
            "sensors = ['temperature', 'vibration', 'pressure', 'rpm', 'oil_level']\n",
            "colors  = ['#00d4ff', '#ff4757', '#2ed573', '#ffa502', '#a29bfe']\n",
            "\n",
            "for ax, col, color in zip(axes, sensors, colors):\n",
            "    ax.plot(mdf['timestamp'], mdf[col], color=color, linewidth=0.8)\n",
            "    fail_m = mdf['failure'] == 1\n",
            "    ax.scatter(mdf.loc[fail_m, 'timestamp'], mdf.loc[fail_m, col],\n",
            "               color='red', s=20, zorder=5, label='Failure')\n",
            "    ax.set_ylabel(col, fontsize=9)\n",
            "    ax.grid(alpha=0.3)\n",
            "\n",
            "plt.suptitle('Machine #1 — Sensor Readings Over Time', fontweight='bold')\n",
            "plt.tight_layout()\n",
            "plt.savefig('../outputs/images/nb_sensor_timeseries.png', dpi=120, bbox_inches='tight')\n",
            "plt.show()",
        ],
        "metadata": {},
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "source": [
            "# Correlation heatmap\n",
            "sensor_cols = ['temperature', 'vibration', 'pressure', 'rpm', 'oil_level', 'failure']\n",
            "corr = df[sensor_cols].corr()\n",
            "\n",
            "plt.figure(figsize=(8, 6))\n",
            "sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm', center=0,\n",
            "            linewidths=0.5, annot_kws={'size': 10})\n",
            "plt.title('Sensor Feature Correlation Matrix', fontweight='bold')\n",
            "plt.tight_layout()\n",
            "plt.savefig('../outputs/images/nb_correlation.png', dpi=120, bbox_inches='tight')\n",
            "plt.show()",
        ],
        "metadata": {},
        "outputs": [],
        "execution_count": None,
    },
    # ─── Feature Engineering ─────────────────────────────────
    {
        "cell_type": "markdown",
        "source": [
            "## 🧮 Step 5: Feature Engineering\n",
            "\n",
            "> **Why create features?**  \n",
            "> Raw sensor values alone are limited. We extract patterns:\n",
            "> - **Rolling averages** → smooth trends\n",
            "> - **Lag features** → past sensor states\n",
            "> - **Rate of change** → how fast sensors are changing\n",
            "> - **Interaction features** → combined sensor stress",
        ],
        "metadata": {},
    },
    {
        "cell_type": "code",
        "source": [
            "df = feature_engineering_pipeline(df)\n",
            "feature_cols = get_feature_columns(df)\n",
            "\n",
            "print(f'Total features created: {len(feature_cols)}')\n",
            "print('\\nSample features:')\n",
            "print(feature_cols[:15])\n",
            "print('...')\n",
            "print(feature_cols[-5:])",
        ],
        "metadata": {},
        "outputs": [],
        "execution_count": None,
    },
    # ─── Model Training ──────────────────────────────────────
    {
        "cell_type": "markdown",
        "source": [
            "## 🧠 Step 6: Model Training\n",
            "\n",
            "> **Three models are compared:**\n",
            "> 1. **Logistic Regression** — simple baseline, good explainability\n",
            "> 2. **Random Forest** — handles non-linear patterns, robust\n",
            "> 3. **Gradient Boosting** — typically highest accuracy on tabular data\n",
            "\n",
            "> **SMOTE** is used to balance the dataset (failures are rare ~5%)",
        ],
        "metadata": {},
    },
    {
        "cell_type": "code",
        "source": [
            "X_train, X_test, y_train, y_test, scaler = prepare_data(df, feature_cols)\n",
            "results, best_model, best_metrics, all_metrics = train_all_models(\n",
            "    X_train, X_test, y_train, y_test\n",
            ")\n",
            "save_model(best_model, scaler, feature_cols, save_dir='../models')",
        ],
        "metadata": {},
        "outputs": [],
        "execution_count": None,
    },
    # ─── Evaluation ──────────────────────────────────────────
    {
        "cell_type": "markdown",
        "source": [
            "## 📈 Step 7: Model Evaluation\n",
            "\n",
            "> **Why is Recall important?**  \n",
            "> In predictive maintenance, a **missed failure is catastrophic**.  \n",
            "> We prefer a model with high RECALL even if it means some false alarms.",
        ],
        "metadata": {},
    },
    {
        "cell_type": "code",
        "source": [
            "# Model comparison bar chart\n",
            "models_names = [m['model'] for m in all_metrics]\n",
            "f1_scores    = [m['f1']    for m in all_metrics]\n",
            "recalls      = [m['recall'] for m in all_metrics]\n",
            "aucs         = [m['roc_auc'] for m in all_metrics]\n",
            "\n",
            "x     = range(len(models_names))\n",
            "width = 0.25\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(10, 5))\n",
            "ax.bar([i - width for i in x], f1_scores, width, label='F1 Score',  color='#00d4ff')\n",
            "ax.bar(x,                       recalls,   width, label='Recall',    color='#ff4757')\n",
            "ax.bar([i + width for i in x], aucs,      width, label='ROC-AUC', color='#2ed573')\n",
            "ax.set_xticks(x)\n",
            "ax.set_xticklabels(models_names)\n",
            "ax.set_ylabel('Score')\n",
            "ax.set_title('Model Comparison', fontweight='bold')\n",
            "ax.legend()\n",
            "ax.set_ylim(0, 1.1)\n",
            "ax.grid(axis='y', alpha=0.3)\n",
            "plt.tight_layout()\n",
            "plt.savefig('../outputs/images/nb_model_comparison.png', dpi=120, bbox_inches='tight')\n",
            "plt.show()",
        ],
        "metadata": {},
        "outputs": [],
        "execution_count": None,
    },
    # ─── Predictions ─────────────────────────────────────────
    {
        "cell_type": "markdown",
        "source": ["## 🚨 Step 8: Failure Prediction & Alert System"],
        "metadata": {},
    },
    {
        "cell_type": "code",
        "source": [
            "df_pred = predict_failure(df, best_model, scaler, feature_cols)\n",
            "\n",
            "# Show failure probability for Machine 1\n",
            "mdf = df_pred[df_pred['machine_id'] == 1]\n",
            "\n",
            "plt.figure(figsize=(14, 4))\n",
            "plt.fill_between(mdf['timestamp'], mdf['failure_prob'], alpha=0.4, color='#ff4757')\n",
            "plt.plot(mdf['timestamp'], mdf['failure_prob'], color='#ff4757', linewidth=1, label='Failure Probability')\n",
            "plt.axhline(0.5, color='orange', linestyle='--', label='Alert Threshold (50%)')\n",
            "plt.axhline(0.75, color='red',   linestyle=':', linewidth=1.5, label='Critical (75%)')\n",
            "plt.xlabel('Timestamp')\n",
            "plt.ylabel('Failure Probability')\n",
            "plt.title('Machine #1 — Predicted Failure Probability Over Time', fontweight='bold')\n",
            "plt.legend()\n",
            "plt.grid(alpha=0.3)\n",
            "plt.tight_layout()\n",
            "plt.savefig('../outputs/images/nb_failure_prob.png', dpi=120, bbox_inches='tight')\n",
            "plt.show()",
        ],
        "metadata": {},
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "source": [
            "# Generate and display alerts\n",
            "alerts = generate_alerts(df_pred)\n",
            "print_alert_summary(alerts)\n",
            "print(f'\\nTop 10 Alerts:')\n",
            "alerts.head(10)",
        ],
        "metadata": {},
        "outputs": [],
        "execution_count": None,
    },
    # ─── Conclusion ──────────────────────────────────────────
    {
        "cell_type": "markdown",
        "source": [
            "## ✅ Step 9: Conclusion & Key Learnings\n",
            "\n",
            "### What we built:\n",
            "- ✅ **Virtual IoT Sensor Simulation** — realistic degradation patterns\n",
            "- ✅ **Full ML Pipeline** — from raw data to predictions\n",
            "- ✅ **SMOTE Balancing** — handles rare failure events\n",
            "- ✅ **3 Competing Models** — automatically selects the best\n",
            "- ✅ **Alert System** — ML + rule-based hybrid\n",
            "- ✅ **Rich Visualizations** — 10 production-quality charts\n",
            "\n",
            "### Industry Takeaways:\n",
            "| Metric | Typical Industry Goal |\n",
            "|--------|----------------------|\n",
            "| Recall | > 85% (don't miss failures) |\n",
            "| Precision | > 70% (avoid too many false alarms) |\n",
            "| ROC-AUC | > 0.85 (good discrimination) |\n",
            "\n",
            "### Next Steps (to extend this project):\n",
            "- 🔹 Add LSTM for time-series deep learning\n",
            "- 🔹 Connect to real dataset: [NASA CMAPSS](https://data.nasa.gov/)\n",
            "- 🔹 Build a Streamlit web dashboard\n",
            "- 🔹 Deploy with FastAPI for real-time predictions",
        ],
        "metadata": {},
    },
]

notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "version": "3.11.0",
        },
    },
    "cells": [],
}

for cell in cells:
    if cell["cell_type"] == "markdown":
        notebook["cells"].append({
            "cell_type": "markdown",
            "id": f"cell-{len(notebook['cells'])}",
            "metadata": {},
            "source": cell["source"],
        })
    else:
        notebook["cells"].append({
            "cell_type": "code",
            "id": f"cell-{len(notebook['cells'])}",
            "metadata": {},
            "source": cell["source"],
            "outputs": [],
            "execution_count": None,
        })

output_path = os.path.join(os.path.dirname(__file__),
                            "predictive_maintenance_analysis.ipynb")
with open(output_path, "w") as f:
    json.dump(notebook, f, indent=2)

print(f"[OK] Notebook created: {output_path}")
